from __future__ import annotations

DEFAULT_LANG = "en"
SUPPORTED_LANGS = ("uz", "en")

LANG_NAMES = {"uz": "O'zbekcha", "en": "English"}


def detect_lang(telegram_language_code: str | None) -> str:
    if telegram_language_code and telegram_language_code.lower().startswith("uz"):
        return "uz"
    return "en"


_STRINGS: dict[str, dict[str, str]] = {
    # ---- Start / menu ----
    "welcome": {
        "en": "👋 Welcome! This bot lets people send you anonymous messages.\n\nShare your personal link and start receiving messages.",
        "uz": "👋 Xush kelibsiz! Ushbu bot orqali sizga odamlar anonim xabar yubora olishadi.\n\nShaxsiy havolangizni ulashing va xabarlar qabul qilishni boshlang.",
    },
    "main_menu": {"en": "🏠 Main menu", "uz": "🏠 Asosiy menyu"},
    "btn_my_link": {"en": "🔗 My link", "uz": "🔗 Havolam"},
    "btn_settings": {"en": "⚙️ Settings", "uz": "⚙️ Sozlamalar"},
    "btn_stats": {"en": "📊 Statistics", "uz": "📊 Statistika"},
    "btn_blocked": {"en": "🚫 Blocked senders", "uz": "🚫 Bloklangan foydalanuvchilar"},
    "btn_premium": {"en": "⭐ Get Premium", "uz": "⭐ Premium olish"},
    "btn_admin_panel": {"en": "🛠 Admin panel", "uz": "🛠 Admin panel"},
    "btn_share_link": {"en": "📤 Share link", "uz": "📤 Havolani ulashish"},
    "btn_regenerate_link": {"en": "♻️ Regenerate link", "uz": "♻️ Havolani yangilash"},
    "btn_back": {"en": "⬅️ Back", "uz": "⬅️ Orqaga"},
    "btn_pause": {"en": "⏸ Pause messages", "uz": "⏸ Xabarlarni to'xtatish"},
    "btn_resume": {"en": "▶️ Resume messages", "uz": "▶️ Xabarlarni davom ettirish"},
    "btn_notify_on": {"en": "🔔 Enable notifications", "uz": "🔔 Bildirishnomalarni yoqish"},
    "btn_notify_off": {"en": "🔕 Disable notifications", "uz": "🔕 Bildirishnomalarni o'chirish"},
    "btn_language": {"en": "🌐 Language", "uz": "🌐 Til"},
    "btn_cancel": {"en": "✖️ Cancel", "uz": "✖️ Bekor qilish"},

    "your_own_link": {
        "en": "This is your own link — share it with others to receive anonymous messages!",
        "uz": "Bu sizning shaxsiy havolangiz — anonim xabarlar olish uchun uni boshqalarga ulashing!",
    },
    "link_invalid": {
        "en": "This anonymous link is invalid or has been regenerated by its owner.",
        "uz": "Ushbu anonim havola yaroqsiz yoki egasi tomonidan yangilangan.",
    },
    "receiver_unavailable": {"en": "This user is not available.", "uz": "Ushbu foydalanuvchi mavjud emas."},
    "receiver_paused": {
        "en": "This user has temporarily paused anonymous messages. Try again later.",
        "uz": "Ushbu foydalanuvchi anonim xabarlarni vaqtincha to'xtatgan. Keyinroq urinib ko'ring.",
    },
    "send_prompt": {
        "en": "💬 Send an <b>anonymous</b> message to <b>{name}</b>.\n\nYou can send text, a photo, or a voice message. They will never see who you are.",
        "uz": "💬 <b>{name}</b>ga <b>anonim</b> xabar yuboring.\n\nMatn, rasm yoki ovozli xabar yuborishingiz mumkin. Ular sizning kimligingizni hech qachon bilishmaydi.",
    },
    "info_anonymous": {
        "en": "Your identity is hidden. The receiver cannot see who you are unless they have Premium AND you send after they activated it.",
        "uz": "Sizning shaxsingiz yashiringan. Qabul qiluvchi Premiumga ega bo'lmasa va siz uning Premiumi faollashtirilgandan keyin yozmasangiz, sizni ko'ra olmaydi.",
    },
    "cancelled": {"en": "Cancelled.", "uz": "Bekor qilindi."},

    # ---- Link ----
    "your_link": {
        "en": "🔗 Your personal anonymous link:\n\n<code>{url}</code>\n\nShare it anywhere — anyone who opens it can send you an anonymous message.",
        "uz": "🔗 Sizning shaxsiy anonim havolangiz:\n\n<code>{url}</code>\n\nUni istalgan joyda ulashing — uni ochgan har bir kishi sizga anonim xabar yubora oladi.",
    },
    "link_regenerated": {
        "en": "♻️ Link regenerated. Your old link no longer works.\n\n<code>{url}</code>",
        "uz": "♻️ Havola yangilandi. Eski havolangiz endi ishlamaydi.\n\n<code>{url}</code>",
    },
    "new_link_generated": {"en": "New link generated", "uz": "Yangi havola yaratildi"},

    # ---- Settings ----
    "settings_title": {"en": "⚙️ Settings", "uz": "⚙️ Sozlamalar"},
    "messages_paused": {"en": "Messages paused", "uz": "Xabarlar to'xtatildi"},
    "messages_resumed": {"en": "Messages resumed", "uz": "Xabarlar davom ettirildi"},
    "notifications_on": {"en": "Notifications on", "uz": "Bildirishnomalar yoqildi"},
    "notifications_off": {"en": "Notifications off", "uz": "Bildirishnomalar o'chirildi"},
    "choose_language": {"en": "🌐 Choose your language:", "uz": "🌐 Tilni tanlang:"},
    "language_updated": {"en": "✅ Language updated.", "uz": "✅ Til o'zgartirildi."},

    # ---- Anonymous send ----
    "link_session_expired": {
        "en": "This link session expired. Please open the anonymous link again.",
        "uz": "Havola sessiyasi muddati tugadi. Iltimos, anonim havolani qaytadan oching.",
    },
    "rate_limited": {
        "en": "⏳ You're sending messages too fast. Please wait a bit and try again.",
        "uz": "⏳ Siz juda tez xabar yuboryapsiz. Iltimos, biroz kuting va qayta urinib ko'ring.",
    },
    "sender_blocked": {
        "en": "You are not able to send messages to this user.",
        "uz": "Siz ushbu foydalanuvchiga xabar yubora olmaysiz.",
    },
    "photo_too_large": {"en": "Photo is too large (max 10 MB).", "uz": "Rasm hajmi juda katta (maksimal 10 MB)."},
    "voice_too_long": {"en": "Voice message is too long (max 60 seconds).", "uz": "Ovozli xabar juda uzun (maksimal 60 soniya)."},
    "voice_too_large": {"en": "Voice message is too large (max 2 MB).", "uz": "Ovozli xabar hajmi juda katta (maksimal 2 MB)."},
    "unsupported_content": {
        "en": "Unsupported message type. Please send text, a photo, or a voice message.",
        "uz": "Qo'llab-quvvatlanmaydigan xabar turi. Iltimos, matn, rasm yoki ovozli xabar yuboring.",
    },
    "duplicate_message": {
        "en": "You already sent this exact message recently. Try saying something new!",
        "uz": "Siz bu xabarni yaqinda allaqachon yuborgansiz. Boshqa narsa yozib ko'ring!",
    },
    "message_delivered": {"en": "✅ Your anonymous message has been delivered!", "uz": "✅ Anonim xabaringiz yetkazildi!"},
    "new_anonymous_message": {"en": "📩 <b>New anonymous message</b>", "uz": "📩 <b>Yangi anonim xabar</b>"},

    # ---- Reply ----
    "reply_prompt": {
        "en": "✍️ Send your reply (text, photo, or voice). It will be delivered anonymously as a reply.",
        "uz": "✍️ Javobingizni yuboring (matn, rasm yoki ovozli). U anonim tarzda javob sifatida yetkaziladi.",
    },
    "message_not_found": {"en": "Message not found.", "uz": "Xabar topilmadi."},
    "reply_session_expired": {"en": "Reply session expired.", "uz": "Javob berish sessiyasi muddati tugadi."},
    "original_gone": {"en": "Original message no longer exists.", "uz": "Asl xabar endi mavjud emas."},
    "reply_sent": {"en": "✅ Reply sent.", "uz": "✅ Javob yuborildi."},
    "reply_delivery_failed": {
        "en": "⚠️ Could not deliver the reply — the sender may have blocked the bot.",
        "uz": "⚠️ Javobni yetkazib bo'lmadi — yuboruvchi botni bloklagan bo'lishi mumkin.",
    },
    "reply_header": {"en": "💬 <b>Reply to your anonymous message:</b>", "uz": "💬 <b>Anonim xabaringizga javob:</b>"},
    "reply_caption": {"en": "💬 Reply to your anonymous message", "uz": "💬 Anonim xabaringizga javob"},

    # ---- Reveal / block / report ----
    "reveal_locked": {
        "en": "This message was received before Premium was activated, so it stays anonymous.",
        "uz": "Ushbu xabar Premium faollashtirilishidan oldin qabul qilingan, shuning uchun u anonim bo'lib qoladi.",
    },
    "reveal_result": {"en": "Sender: {identity}{username}", "uz": "Yuboruvchi: {identity}{username}"},
    "already_blocked": {"en": "Already blocked.", "uz": "Allaqachon bloklangan."},
    "sender_now_blocked": {
        "en": "🚫 This sender is now blocked and can no longer message you.",
        "uz": "🚫 Ushbu yuboruvchi endi bloklandi va sizga xabar yubora olmaydi.",
    },
    "report_why": {"en": "⚠️ Why are you reporting this message?", "uz": "⚠️ Nima uchun ushbu xabarni shikoyat qilyapsiz?"},
    "report_submitted": {
        "en": "✅ Report submitted ({reason}). Our admins will review it.",
        "uz": "✅ Shikoyat yuborildi ({reason}). Administratorlarimiz uni ko'rib chiqadi.",
    },
    "report_reason_spam": {"en": "Spam", "uz": "Spam"},
    "report_reason_harassment": {"en": "Harassment", "uz": "Ta'qib qilish"},
    "report_reason_threat": {"en": "Threat", "uz": "Tahdid"},
    "report_reason_other": {"en": "Other", "uz": "Boshqa"},

    "blocked_feature_premium": {"en": "This is a Premium feature.", "uz": "Bu Premium funksiyasi."},
    "no_blocked_users": {"en": "🚫 You haven't blocked anyone.", "uz": "🚫 Siz hali hech kimni bloklamagansiz."},
    "blocked_list_title": {"en": "🚫 Blocked senders:", "uz": "🚫 Bloklangan foydalanuvchilar:"},
    "unblock_btn": {"en": "Unblock {id}", "uz": "Blokdan chiqarish {id}"},
    "unblocked": {"en": "Unblocked.", "uz": "Blokdan chiqarildi."},

    # ---- Premium ----
    "premium_feature_locked": {
        "en": "This is a Premium feature. Get Premium to unlock analytics.",
        "uz": "Bu Premium funksiyasi. Statistikani ochish uchun Premium sotib oling.",
    },
    "premium_plans_header": {
        "en": "⭐ <b>Premium plans</b>\n\nPremium lets you see who sends you NEW anonymous messages, view detailed analytics, and block specific senders.",
        "uz": "⭐ <b>Premium tariflar</b>\n\nPremium sizga YANGI anonim xabar yuboruvchilarni ko'rish, batafsil statistikani kuzatish va aloxida foydalanuvchilarni bloklash imkonini beradi.",
    },
    "premium_not_configured": {"en": "Premium plans are not configured yet.", "uz": "Premium tariflar hali sozlanmagan."},
    "plan_unavailable": {"en": "This plan is no longer available.", "uz": "Ushbu tarif endi mavjud emas."},
    "invoice_description": {
        "en": "Unlock Premium for {days} day(s): see who sends new anonymous messages, detailed analytics, and sender blocking.",
        "uz": "{days} kunlik Premiumni oching: kimlar yangi anonim xabar yuborayotganini ko'ring, batafsil statistika va foydalanuvchilarni bloklash imkoniyati.",
    },
    "invoice_invalid": {
        "en": "This invoice is no longer valid. Please try again.",
        "uz": "Ushbu hisob-faktura endi amal qilmaydi. Iltimos, qaytadan urinib ko'ring.",
    },
    "payment_unmatched": {
        "en": "Payment received, but we couldn't match it automatically. Please contact support.",
        "uz": "To'lov qabul qilindi, lekin uni avtomatik moslay olmadik. Iltimos, qo'llab-quvvatlash xizmatiga murojaat qiling.",
    },
    "premium_activated": {
        "en": "🎉 Premium activated! Plan: <b>{plan}</b>\nExpires: <b>{expires}</b>\n\nYou can now see who sends you NEW anonymous messages, view analytics, and block senders.",
        "uz": "🎉 Premium faollashtirildi! Tarif: <b>{plan}</b>\nMuddati: <b>{expires}</b>\n\nEndi siz kimlar YANGI anonim xabar yuborayotganini ko'rishingiz, statistikani kuzatishingiz va foydalanuvchilarni bloklashingiz mumkin.",
    },

    # ---- Stats ----
    "stats_title": {"en": "📊 Statistics", "uz": "📊 Statistika"},
    "btn_stats_daily": {"en": "📅 Daily", "uz": "📅 Kunlik"},
    "btn_stats_weekly": {"en": "🗓 Weekly", "uz": "🗓 Haftalik"},
    "btn_stats_yearly": {"en": "📈 Yearly", "uz": "📈 Yillik"},
    "btn_stats_top": {"en": "🏆 Top senders", "uz": "🏆 Faol yuboruvchilar"},
    "stats_daily_title": {"en": "📅 <b>Today</b>", "uz": "📅 <b>Bugun</b>"},
    "stats_received": {"en": "Received", "uz": "Qabul qilindi"},
    "stats_answered": {"en": "Answered", "uz": "Javob berildi"},
    "stats_voice": {"en": "Voice", "uz": "Ovozli"},
    "stats_photos": {"en": "Photos", "uz": "Rasmlar"},
    "stats_avg_response": {"en": "Avg. response time", "uz": "O'rtacha javob vaqti"},
    "stats_weekly_title": {"en": "🗓 <b>This week</b>", "uz": "🗓 <b>Shu hafta</b>"},
    "stats_total_messages": {"en": "Total messages", "uz": "Jami xabarlar"},
    "stats_growth": {"en": "Growth vs last week", "uz": "O'tgan haftaga nisbatan o'sish"},
    "stats_most_active_day": {"en": "Most active day", "uz": "Eng faol kun"},
    "stats_answer_rate": {"en": "Answer rate", "uz": "Javob berish darajasi"},
    "stats_yearly_title": {"en": "📈 <b>This year</b>", "uz": "📈 <b>Shu yil</b>"},
    "stats_no_data": {"en": "No data yet.", "uz": "Hozircha ma'lumot yo'q."},
    "stats_total_replies": {"en": "Total replies", "uz": "Jami javoblar"},
    "stats_best_month": {"en": "Best month", "uz": "Eng faol oy"},
    "top_senders_title": {"en": "🏆 <b>Top senders</b>", "uz": "🏆 <b>Faol yuboruvchilar</b>"},
    "no_revealable_senders": {
        "en": "No revealable senders yet — only messages received while Premium is active can show a name.",
        "uz": "Hozircha ismini ko'rsatish mumkin bo'lgan yuboruvchilar yo'q — faqat Premium faol bo'lganda qabul qilingan xabarlar nomini ko'rsatadi.",
    },
    "most_active_hours": {"en": "⏰ <b>Most active hours:</b>", "uz": "⏰ <b>Eng faol soatlar:</b>"},

    # ---- Admin ----
    "access_denied": {"en": "Access denied.", "uz": "Kirish rad etildi."},
    "admin_panel_title": {"en": "🛠 Admin panel", "uz": "🛠 Admin panel"},
    "btn_admin_overview": {"en": "📊 Overview", "uz": "📊 Umumiy holat"},
    "btn_admin_broadcast": {"en": "📢 Broadcast", "uz": "📢 Xabar tarqatish"},
    "btn_admin_reports": {"en": "⚠️ Reports", "uz": "⚠️ Shikoyatlar"},
    "btn_admin_prices": {"en": "💰 Manage prices", "uz": "💰 Narxlarni boshqarish"},
    "btn_admin_manage_admins": {"en": "👮 Manage admins", "uz": "👮 Adminlarni boshqarish"},
    "admin_overview_title": {"en": "📊 <b>Overview</b>", "uz": "📊 <b>Umumiy holat</b>"},
    "overview_total_users": {"en": "Total users", "uz": "Jami foydalanuvchilar"},
    "overview_active_7d": {"en": "Active (7d)", "uz": "Faol (7 kun)"},
    "overview_premium_users": {"en": "Premium users", "uz": "Premium foydalanuvchilar"},
    "overview_revenue": {"en": "Revenue", "uz": "Daromad"},
    "no_open_reports": {"en": "✅ No open reports.", "uz": "✅ Ochiq shikoyatlar yo'q."},
    "report_info": {
        "en": "⚠️ Report #{id}\nReason: {reason}\n\nMessage: {preview}\n\nRemaining open reports: {count}",
        "uz": "⚠️ Shikoyat #{id}\nSabab: {reason}\n\nXabar: {preview}\n\nQolgan ochiq shikoyatlar: {count}",
    },
    "btn_ban_sender": {"en": "🔨 Ban sender", "uz": "🔨 Yuboruvchini bloklash"},
    "btn_dismiss": {"en": "✅ Dismiss", "uz": "✅ Rad etish"},
    "sender_banned": {"en": "Sender banned.", "uz": "Yuboruvchi bloklandi."},
    "report_not_found": {"en": "Report not found.", "uz": "Shikoyat topilmadi."},
    "dismissed": {"en": "Dismissed.", "uz": "Rad etildi."},
    "ban_usage": {"en": "Usage: /ban <telegram_id>", "uz": "Foydalanish: /ban <telegram_id>"},
    "unban_usage": {"en": "Usage: /unban <telegram_id>", "uz": "Foydalanish: /unban <telegram_id>"},
    "user_not_found": {"en": "User not found.", "uz": "Foydalanuvchi topilmadi."},
    "user_banned": {"en": "🔨 Banned user {id}.", "uz": "🔨 Foydalanuvchi {id} bloklandi."},
    "user_unbanned": {"en": "✅ Unbanned user {id}.", "uz": "✅ Foydalanuvchi {id} blokdan chiqarildi."},
    "manage_prices_title": {"en": "💰 Manage plan prices (tap to edit):", "uz": "💰 Tarif narxlarini boshqarish (o'zgartirish uchun bosing):"},
    "price_prompt": {
        "en": "Send the new Stars price for plan '{code}' (integer):",
        "uz": "'{code}' tarifi uchun yangi Stars narxini yuboring (butun son):",
    },
    "price_positive_int": {"en": "Please send a positive integer.", "uz": "Iltimos, musbat butun son yuboring."},
    "plan_not_found": {"en": "Plan not found.", "uz": "Tarif topilmadi."},
    "price_updated": {"en": "✅ Updated '{name}' price to {price}⭐.", "uz": "✅ '{name}' tarifi narxi {price}⭐ ga o'zgartirildi."},
    "broadcast_prompt": {
        "en": "📢 Send the broadcast content: plain text, or a photo with a caption.",
        "uz": "📢 Tarqatiladigan xabarni yuboring: oddiy matn yoki tavsif bilan rasm.",
    },
    "broadcast_preview": {
        "en": "Preview ({kind}):\n\n{preview}\n\nSend to ALL non-banned users?",
        "uz": "Ko'rib chiqish ({kind}):\n\n{preview}\n\nBarcha bloklanmagan foydalanuvchilarga yuborilsinmi?",
    },
    "broadcast_kind_text": {"en": "text", "uz": "matn"},
    "broadcast_kind_photo": {"en": "photo + text", "uz": "rasm + matn"},
    "broadcast_no_caption": {"en": "(no caption)", "uz": "(tavsif yo'q)"},
    "btn_send_now": {"en": "✅ Send now", "uz": "✅ Hozir yuborish"},
    "broadcast_done": {
        "en": "✅ Broadcast finished.\nSent: {sent}\nFailed: {failed}\nTotal targets: {total}",
        "uz": "✅ Xabar tarqatish yakunlandi.\nYuborildi: {sent}\nXato: {failed}\nJami: {total}",
    },

    # ---- Admin management (super admin only) ----
    "super_admin_only": {
        "en": "Only the super admin can manage other admins.",
        "uz": "Boshqa adminlarni faqat super admin boshqarishi mumkin.",
    },
    "manage_admins_title": {"en": "👮 <b>Admins</b>", "uz": "👮 <b>Adminlar</b>"},
    "no_admins": {"en": "No appointed admins yet.", "uz": "Hozircha tayinlangan adminlar yo'q."},
    "btn_add_admin": {"en": "➕ Add admin", "uz": "➕ Admin qo'shish"},
    "btn_remove_admin": {"en": "➖ Remove {name}", "uz": "➖ {name}ni olib tashlash"},
    "add_admin_prompt": {
        "en": "Send the Telegram user ID to grant admin rights to. The user must have started this bot at least once.",
        "uz": "Admin huquqini beriladigan foydalanuvchining Telegram ID raqamini yuboring. Foydalanuvchi botni kamida bir marta ishga tushirgan bo'lishi kerak.",
    },
    "add_admin_invalid": {"en": "Please send a valid numeric Telegram ID.", "uz": "Iltimos, to'g'ri raqamli Telegram ID yuboring."},
    "add_admin_user_unknown": {
        "en": "That user hasn't started the bot yet, so they can't be made an admin.",
        "uz": "Ushbu foydalanuvchi hali botni ishga tushirmagan, shuning uchun uni admin qila olmaymiz.",
    },
    "add_admin_already": {"en": "That user is already an admin.", "uz": "Ushbu foydalanuvchi allaqachon admin."},
    "add_admin_is_super": {"en": "That user is the super admin already.", "uz": "Ushbu foydalanuvchi allaqachon super admin."},
    "admin_added": {"en": "✅ {name} is now an admin.", "uz": "✅ {name} endi admin."},
    "admin_removed": {"en": "✅ {name} is no longer an admin.", "uz": "✅ {name} endi admin emas."},
    "admin_usage": {"en": "Usage: /addadmin <telegram_id>", "uz": "Foydalanish: /addadmin <telegram_id>"},
    "removeadmin_usage": {"en": "Usage: /removeadmin <telegram_id>", "uz": "Foydalanish: /removeadmin <telegram_id>"},
}


def t(key: str, lang: str | None, **kwargs) -> str:
    lang = lang if lang in SUPPORTED_LANGS else DEFAULT_LANG
    entry = _STRINGS.get(key)
    if entry is None:
        return key
    template = entry.get(lang) or entry.get(DEFAULT_LANG) or key
    if kwargs:
        try:
            return template.format(**kwargs)
        except (KeyError, IndexError):
            return template
    return template
